version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "28017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./docker/qdrant_data:/qdrant/storage
    networks:
      - backend

networks:
  backend: